name: "Feature Request"
description: "Suggest an idea for this project."
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a new feature! Please provide as much detail as possible.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      description: "Please ensure you have completed the following steps."
      options:
        - label: "I have searched the existing issues and have not found a similar feature request."
          required: true

  - type: textarea
    id: problem-description
    attributes:
      label: "Is your feature request related to a problem?"
      description: "A clear and concise description of what the problem is."
      placeholder: "I'm having trouble with..."
    validations:
      required: true

  - type: textarea
    id: solution-description
    attributes:
      label: "Describe the solution you'd like"
      description: "A clear and concise description of what you want to happen."
      placeholder: "I would like to be able to..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Describe alternatives you've considered"
      description: "A clear and concise description of any alternative solutions or features you've considered."
      placeholder: "I've also considered..."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."