name: "Feature Request"
description: "Suggest an improvement."
labels: ["enhancement"]
body:
  - type: textarea
    id: proposal
    attributes:
      label: "What would you like?"
      description: "The change you're proposing."
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: "Why?"
      description: "The problem it solves or the use case it enables."
